version: '3.8'

services:
  web:
    image: ruby-task-image
    ports:
      - "13001:3000"
    volumes:
      - ./order-api:/www
    environment:
      - RAILS_ENV=production
    command: bundle exec rails server -b 0.0.0.0 -p 3000
